[package]
name = "lunar-posadas"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.0"
bevy_asset_loader = {version = "0.22.0", features = ["2d"]}
rand = "0.9.1" # Procedural generation and traits
bevy_enhanced_input = "0.11.0"

[profile.dev.package."*"]
opt-level = 3